packages:
  - "modules/xq-common-kit"
  - "modules/xq-test-utils"
  - "modules/xq-test-infra"
  - "modules/xq-test-harness"
  - "modules/xq-test-harness-e2e-consumer"
  - "modules/xq-octopus"

confirmModulesPurge: false
autoInstallPeers: false

onlyBuiltDependencies:
  - "unrs-resolver"

allowBuilds:
  unrs-resolver: true
