name: ios-example
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
settings:
  base:
    MARKETING_VERSION: 0.1.0
    CURRENT_PROJECT_VERSION: 1
targets:
  ios-example:
    type: application
    platform: iOS
    sources:
      - App
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.ios-example
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
  ios-exampleTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - AppTests
    dependencies:
      - target: ios-example
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.ios-exampleTests
        GENERATE_INFOPLIST_FILE: YES

schemes:
  ios-example:
    build:
      targets:
        ios-example: all
    test:
      targets:
        - ios-exampleTests
