name: CI xq-common-kit

on:
  pull_request:
    paths: &paths
      - modules/xq-common-kit/**
      - modules.yaml
      - scripts/module
      - scripts/check-xq-version-changes.js
      - modules/tsconfig.base.json
      - modules/yarnrc.github-packages.yml
      - .github/workflows/ci-xq-common-kit.yml
      - .github/workflows/module-*.yml
  push:
    branches: [main]
    paths: *paths

concurrency:
  group: ci-xq-common-kit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/module-ci-node.yml
    with:
      module: xq-common-kit
