name: CI xq-skills

on:
  pull_request:
    paths: &paths
      - modules/xq-skills/**
      - modules.yaml
      - modules/xq-skills/version.yaml
      - scripts/module
      - scripts/check-registry-version-changes.py
      - scripts/validate-module-versions.py
      - .github/workflows/ci-xq-skills.yml
      - .github/workflows/module-*.yml
  push:
    branches: [main]
    paths: *paths

concurrency:
  group: ci-xq-skills-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/module-ci-node.yml
    with:
      module: xq-skills
