name: CI xq-test-harness-e2e-consumer

on:
  pull_request:
    paths: &paths
      - modules/xq-test-harness-e2e-consumer/**
      - modules/xq-test-harness/**
      - modules.yaml
      - scripts/module
      - modules/tsconfig.base.json
      - modules/yarnrc.github-packages.yml
      - .github/workflows/ci-xq-test-harness-e2e-consumer.yml
      - .github/workflows/module-*.yml
  push:
    branches: [main]
    paths: *paths

concurrency:
  group: ci-xq-test-harness-e2e-consumer-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/module-ci-node.yml
    with:
      module: xq-test-harness-e2e-consumer
      playwright_skip_browser: true
